// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "SYSLIB1045:'GeneratedRegexAttribute' に変換します。", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.Helper.GetAuthorId(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Models.LanguageUtils.TranslateData")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.ItemUtils.GetItemFolderInfo(System.String,System.String)~Avatar_Explorer.Classes.ItemFolderInfo")]
[assembly: SuppressMessage("Style", "IDE0057:範囲演算子を使用", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.DateUtils.GetDate(System.String)~System.DateTime")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateAvatarList")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.DatabaseUtils.LoadItemsData(System.String)~Avatar_Explorer.Classes.Item[]")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.DatabaseUtils.LoadCommonAvatarData(System.String)~Avatar_Explorer.Classes.CommonAvatar[]")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.AEUtils.GetSearchFilter(System.String)~Avatar_Explorer.Classes.SearchFilter")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateItems")]
[assembly: SuppressMessage("Performance", "SYSLIB1045:'GeneratedRegexAttribute' に変換します。", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.AEUtils.GetSearchFilter(System.String)~Avatar_Explorer.Classes.SearchFilter")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.AddItemForm.openFolderButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.AddItemForm.openMaterialFolderButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.MainForm._defaultControlSize")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateAuthorList")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateItems")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.Helper.GetTranslateData(System.String)~System.Collections.Generic.Dictionary{System.String,System.String}")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~P:Avatar_Explorer.Models.Item.SupportedAvatar")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.AddItemForm.AddButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.AvatarItemExplorer_DragDrop(System.Object,System.Windows.Forms.DragEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.SearchItems")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.DatabaseUtils.GetAvatarName(Avatar_Explorer.Classes.Item[],System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.DatabaseUtils.LoadCustomCategoriesData(System.String)~System.String[]")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateAvatarList")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateItemFiles")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateFilteredItem(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Models.DatabaseUtils.LoadCustomCategoriesData(System.String)~System.String[]")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.AddItemForm.SupportedAvatar")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.MainForm._fontFamilies")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateFilteredItem(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateCategoryList")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateCategoryListLeft")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.MainForm._controlNames")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateAuthorList")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateItemCategoryList")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateItemFiles")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateFilteredFolderItems(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.GenerateFilteredFolderItems(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.SearchItems")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.ExportButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.ExportButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.MainForm.LanguageBox_SelectedIndexChanged(System.Object,System.EventArgs)")]
