// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.FixSupportedAvatarPath(Avatar_Explorer.Classes.Item[])~Avatar_Explorer.Classes.Item[]")]
[assembly: SuppressMessage("Performance", "SYSLIB1045:'GeneratedRegexAttribute' に変換します。", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.GetAuthorId(System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Classes.Helper.TranslateData")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.GetItemFolderInfo(System.String,System.String)~Avatar_Explorer.Classes.ItemFolderInfo")]
[assembly: SuppressMessage("Style", "IDE0057:範囲演算子を使用", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.GetDate(System.String)~System.DateTime")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateAvatarList")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.LoadItemsData(System.String)~Avatar_Explorer.Classes.Item[]")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.LoadCommonAvatarData(System.String)~Avatar_Explorer.Classes.CommonAvatar[]")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.GetSearchFilter(System.String)~Avatar_Explorer.Classes.SearchFilter")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateItems")]
[assembly: SuppressMessage("Performance", "SYSLIB1045:'GeneratedRegexAttribute' に変換します。", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.GetSearchFilter(System.String)~Avatar_Explorer.Classes.SearchFilter")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.AddItem.openFolderButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:命名スタイル", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.AddItem.openMaterialFolderButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.Main._defaultControlSize")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateAuthorList")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateItems")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.GetTranslateData(System.String)~System.Collections.Generic.Dictionary{System.String,System.String}")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~P:Avatar_Explorer.Classes.Item.SupportedAvatar")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.AddItem.AddButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Performance", "CA1862:大文字と小文字を区別しない文字列比較を実行するには、'StringComparison' メソッド オーバーロードを使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateFilteredItem(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.AvatarItemExplorer_DragDrop(System.Object,System.Windows.Forms.DragEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.SearchItems")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.GetAvatarName(Avatar_Explorer.Classes.Item[],System.String)~System.String")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.LoadCustomCategoriesData(System.String)~System.String[]")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateAvatarList")]
[assembly: SuppressMessage("Performance", "CA1862:大文字と小文字を区別しない文字列比較を実行するには、'StringComparison' メソッド オーバーロードを使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateFilteredFolderItems(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateItemFiles")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateFilteredItem(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Classes.Helper.LoadCustomCategoriesData(System.String)~System.String[]")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.AddItem.SupportedAvatar")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.Main._fontFamilies")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateFilteredItem(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateCategoryList")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateCategoryListLeft")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.Main._controlNames")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.Main._defaultControlLocation")]
[assembly: SuppressMessage("Style", "IDE0028:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~F:Avatar_Explorer.Forms.Main._defaultFontSize")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateAuthorList")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateItemCategoryList")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateItemFiles")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateFilteredFolderItems(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0039:ローカル関数を使用します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.GenerateFilteredFolderItems(Avatar_Explorer.Classes.SearchFilter)")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.SearchItems")]
[assembly: SuppressMessage("Style", "IDE0301:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.ExportButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.ExportButton_Click(System.Object,System.EventArgs)")]
[assembly: SuppressMessage("Style", "IDE0305:コレクションの初期化を簡略化します", Justification = "<保留中>", Scope = "member", Target = "~M:Avatar_Explorer.Forms.Main.LanguageBox_SelectedIndexChanged(System.Object,System.EventArgs)")]
